In [12]:
import pandas
data = pandas.read_csv("datasets/matchprediction_data.csv")
data

,home_team,away_team,home_possession,away_possession,home_expected goals,away_expected goals,home_shots_per_ninety,away_shots_per_ninety,home_pass_accuracy,away_pass_accuracy,home_form,away_form,h2h_home_win_rate,h2h_draw_rate,h2h_away_win_rate,home_injuries,away_injuries,home_advantage,goal_difference_average,result
0,Arsenal,Chelsea,62,38,2.1,0.9,16,8,89,81,0.80,0.40,0.6,0.2,0.2,0.10,0.2,1.2,1.0,home_win
1,ManUtd,Liverpool,48,52,0.9,1.6,9,14,82,86,0.40,0.70,0.3,0.3,0.4,0.20,0.1,0.9,1.2,away_win
2,ManCity,Tottenham,55,45,1.6,1.1,13,10,86,84,0.70,0.60,0.5,0.3,0.2,0.15,0.1,1.1,0.5,home_win
3,Chelsea,Arsenal,51,49,1.2,1.2,10,11,84,83,0.60,0.60,0.4,0.4,0.2,0.10,0.1,1.0,0.0,draw
4,Liverpool,ManCity,44,56,0.7,2.0,7,15,78,88,0.30,0.80,0.2,0.2,0.6,0.25,0.1,0.8,1.5,away_win
5,Tottenham,ManUtd,67,33,2.5,0.8,18,7,91,80,0.90,0.30,0.7,0.2,0.1,0.05,0.2,1.3,1.8,home_win
6,Arsenal,Liverpool,53,47,1.3,1.3,11,11,85,84,0.60,0.60,0.5,0.3,0.2,0.10,0.1,1.0,0.2,draw
7,Chelsea,ManCity,46,54,0.8,1.9,8,13,80,87,0.40,0.70,0.3,0.3,0.4,0.20,0.1,0.9,1.3,away_win
8,ManUtd,Arsenal,59,41,1.9,1.0,14,9,88,82,0.80,0.50,0.6,0.2,0.2,0.10,0.1,1.2,0.9,home_win
9,Liverpool,Chelsea,50,50,1.1,1.1,10,10,83,83,0.60,0.60,0.4,0.4,0.2,0.10,0.1,1.0,0.0,draw
10,ManCity,ManUtd,62,38,2.2,0.8,17,7,90,79,0.85,0.35,0.6,0.2,0.2,0.10,0.2,1.2,1.1,home_win
11,Tottenham,Chelsea,47,53,0.8,1.8,8,13,81,87,0.40,0.75,0.3,0.3,0.4,0.20,0.1,0.9,1.4,away_win
12,Arsenal,ManCity,56,44,1.5,1.0,12,9,86,83,0.70,0.50,0.5,0.3,0.2,0.10,0.1,1.1,0.4,home_win
13,Chelsea,Liverpool,52,48,1.2,1.2,10,11,84,84,0.60,0.60,0.4,0.4,0.2,0.10,0.1,1.0,0.1,draw
14,ManUtd,Tottenham,45,55,0.7,1.9,7,14,78,88,0.30,0.80,0.2,0.2,0.6,0.25,0.1,0.8,1.6,away_win
15,ManCity,Arsenal,68,32,2.6,0.7,19,6,92,79,0.90,0.30,0.7,0.2,0.1,0.05,0.2,1.3,1.9,home_win
16,Liverpool,ManUtd,54,46,1.4,1.1,11,10,85,84,0.60,0.60,0.5,0.3,0.2,0.10,0.1,1.0,0.3,draw
17,Chelsea,Tottenham,49,51,1.0,1.3,9,12,83,85,0.50,0.70,0.4,0.4,0.2,0.10,0.1,1.0,0.2,away_win
18,Arsenal,ManUtd,60,40,2.0,0.9,15,8,88,81,0.80,0.40,0.6,0.2,0.2,0.10,0.1,1.2,0.8,home_win
19,Liverpool,ManCity,51,49,1.1,1.1,10,10,83,83,0.60,0.60,0.4,0.4,0.2,0.10,0.1,1.0,0.0,draw

In [13]:
# Here I described the data
data.describe()

,home_possession,away_possession,home_expected goals,away_expected goals,home_shots_per_ninety,away_shots_per_ninety,home_pass_accuracy,away_pass_accuracy,home_form,away_form,h2h_home_win_rate,h2h_draw_rate,h2h_away_win_rate,home_injuries,away_injuries,home_advantage,goal_difference_average
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000
mean,53.950000,46.050000,1.430000,1.235000,11.700000,10.400000,84.800000,83.550000,0.617500,0.570000,0.45500,0.285000,0.260000,0.127500,0.120000,1.04500,0.810000
std,7.082038,7.082038,0.598331,0.397724,3.672085,2.542274,4.020998,2.742934,0.190066,0.155089,0.15035,0.081273,0.142902,0.059549,0.041039,0.15035,0.643919
min,44.000000,32.000000,0.700000,0.700000,7.000000,6.000000,78.000000,79.000000,0.300000,0.300000,0.20000,0.200000,0.100000,0.050000,0.100000,0.80000,0.000000
25%,48.750000,40.750000,0.975000,0.975000,9.000000,8.750000,82.750000,81.750000,0.475000,0.475000,0.37500,0.200000,0.200000,0.100000,0.100000,0.97500,0.200000
50%,52.500000,47.500000,1.250000,1.100000,10.500000,10.000000,84.500000,83.500000,0.600000,0.600000,0.45000,0.300000,0.200000,0.100000,0.100000,1.00000,0.850000
75%,59.250000,51.250000,1.925000,1.375000,14.250000,12.250000,88.000000,85.250000,0.800000,0.700000,0.60000,0.325000,0.250000,0.162500,0.100000,1.20000,1.325000
max,68.000000,56.000000,2.600000,2.000000,19.000000,15.000000,92.000000,88.000000,0.900000,0.800000,0.70000,0.400000,0.600000,0.250000,0.200000,1.30000,1.900000

In [14]:
# Here I now converted the results from text to number form
# Whereby the home_win = 2, draw = 1 and away_win = 0

data["result"] = data["result"].map({
    "home_win": 2,
    "draw" : 1,
    "away_win" : 0
})

In [20]:
# Here I now donverted my datasets into an array format
array = data.values
# print(array)

# Here I tell the system what features it is to take where by I tell it to pic all rows(:) from column 2(2)(but not including) up to the last column(-1)
# This is like slicing
X = array[:, 2:-1]
# X

# Here I tell the system what I want it to try and predict and in this case it is the results(home_win = 2, draw - 1, away_win = 0)
Y = array[:, -1]
Y

array([2, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 2, 1],
      dtype=object)

In [16]:
# At this point I went ahead and split the data into training(X_train,Y_train) and testing(X_test,Y_test) sets.

from sklearn import model_selection

X_train, X_test, Y_train,Y_test = model_selection.train_test_split(X, Y, test_size=0.2, random_state=42)

In [21]:
# Now I trained the model
# First of all I began by importing the model
from sklearn.tree import DecisionTreeClassifier

# Create the model
model = DecisionTreeClassifier()

# Finally I actually train the model
model.fit(X_train, Y_train)

ValueError: Unknown label type: unknown. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.