In [82]:
# Here I loaded my dataset
import pandas 
data = pandas.read_csv("datasets/football_dataset.csv")
data

,home_team,away_team,home_possession,away_possession,home_xg,away_xg,home_shots_per_ninety,away_shots_per_ninety,home_pass_accuracy,away_pass_accuracy,home_form,away_form,h2h_home_win_rate,h2h_draw_rate,h2h_away_win_rate,home_injuries,away_injuries,home_advantage,goal_difference_average,result
0,Chelsea,Man City,60.2,39.8,1.06,0.61,9.4,14.6,82.9,81.0,0.87,0.72,0.22,0.28,0.50,4,1,1.22,1.16,H
1,Wolves,Brighton,51.5,48.5,1.14,2.21,18.6,7.1,80.5,74.1,1.27,2.26,0.15,0.21,0.64,2,2,1.10,1.63,A
2,Everton,Burnley,41.7,58.3,2.62,0.47,12.1,13.2,89.7,76.0,1.22,0.66,0.43,0.33,0.24,0,1,1.37,-0.29,H
3,Everton,Fulham,42.9,57.1,1.32,1.77,17.8,13.9,73.4,82.0,1.98,1.06,0.33,0.18,0.49,5,5,1.06,1.08,H
4,Arsenal,Brighton,62.7,37.3,2.35,1.18,8.9,16.9,83.3,83.8,1.27,1.65,0.54,0.29,0.17,1,2,0.64,1.35,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Crystal Palace,Man United,52.1,47.9,1.47,1.64,14.1,7.0,91.1,78.6,2.48,1.48,0.14,0.37,0.49,2,4,1.04,0.49,H
496,Man United,Aston Villa,49.4,50.6,1.20,0.92,15.9,11.3,78.7,83.7,1.23,2.61,0.10,0.36,0.54,5,5,0.87,-0.18,A
497,Wolves,Crystal Palace,67.1,32.9,1.36,1.38,17.0,12.6,80.2,68.9,2.83,1.39,0.38,0.16,0.46,3,2,1.27,1.38,H
498,Fulham,Bournemouth,59.3,40.7,1.96,1.11,8.8,10.0,80.5,73.4,1.85,2.62,0.28,0.31,0.41,0,5,1.17,-1.33,D
499,Luton,Everton,66.3,33.7,0.84,0.84,16.1,13.6,75.2,70.6,1.00,2.14,0.29,0.31,0.40,0,4,1.41,1.94,D

In [83]:
# Returns the total number of duplicate rows
duplicate_count = data.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [84]:
# LOOKING FOR MISSING VALUES
data.isnull().sum()

home_team                  0
away_team                  0
home_possession            0
away_possession            0
home_xg                    0
away_xg                    0
home_shots_per_ninety      0
away_shots_per_ninety      0
home_pass_accuracy         0
away_pass_accuracy         0
home_form                  0
away_form                  0
h2h_home_win_rate          0
h2h_draw_rate              0
h2h_away_win_rate          0
home_injuries              0
away_injuries              0
home_advantage             0
goal_difference_average    0
result                     0
dtype: int64

In [85]:
# Describing the data
data.describe()

,home_possession,away_possession,home_xg,away_xg,home_shots_per_ninety,away_shots_per_ninety,home_pass_accuracy,away_pass_accuracy,home_form,away_form,h2h_home_win_rate,h2h_draw_rate,h2h_away_win_rate,home_injuries,away_injuries,home_advantage,goal_difference_average
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,53.066400,46.933600,1.662160,1.411820,15.030400,11.484800,82.059400,78.359200,1.892960,1.673520,0.33640,0.252460,0.411140,2.552000,2.53000,1.024060,0.294960
std,8.735698,8.735698,0.648752,0.624118,3.957545,3.668805,5.723503,6.354054,0.622461,0.665099,0.14282,0.085831,0.169607,1.728952,1.70849,0.277789,1.338807
min,38.100000,32.100000,0.500000,0.300000,8.000000,5.100000,72.000000,68.000000,0.800000,0.500000,0.10000,0.100000,0.030000,0.000000,0.00000,0.510000,-2.000000
25%,45.600000,39.375000,1.127500,0.910000,11.775000,8.575000,76.850000,72.475000,1.360000,1.070000,0.21000,0.180000,0.290000,1.000000,1.00000,0.797500,-0.910000
50%,53.000000,47.000000,1.670000,1.375000,15.050000,11.400000,82.350000,78.450000,1.875000,1.705000,0.33000,0.250000,0.430000,3.000000,3.00000,1.025000,0.390000
75%,60.625000,54.400000,2.220000,1.980000,18.200000,14.500000,86.825000,83.500000,2.440000,2.260000,0.45250,0.330000,0.530000,4.000000,4.00000,1.260000,1.470000
max,67.900000,61.900000,2.800000,2.500000,22.000000,18.000000,92.000000,90.000000,3.000000,2.800000,0.60000,0.400000,0.770000,5.000000,5.00000,1.500000,2.490000

In [86]:
# Here I dropped the team name columns since they are strings and thus cannot be used directly.
data = data.drop(columns=["home_team", "away_team"])

In [87]:


# Separate the data
array = data.values
# print(array)

X = array[:, 0:17]
# print(X)

Y = array[:, 17]
print(Y)

['H ' 'A' 'H' 'H' 'H' 'D' 'H' 'H' 'D' 'H' 'A' 'A' 'H' 'D' 'A' 'D' 'D' 'H'
 'D' 'A' 'H' 'H' 'A' 'A' 'A' 'H' 'D' 'H' 'D' 'H' 'A' 'H' 'H' 'D' 'H' 'A'
 'D' 'A' 'A' 'D' 'H' 'H' 'A' 'D' 'A' 'D' 'D' 'D' 'D' 'H' 'H' 'D' 'D' 'H'
 'H' 'H' 'H' 'D' 'H' 'H' 'D' 'D' 'A' 'A' 'H' 'H' 'H' 'H' 'D' 'D' 'D' 'H'
 'D' 'H' 'A' 'H' 'H' 'H' 'H' 'A' 'D' 'H' 'H' 'D' 'D' 'A' 'H' 'H' 'H' 'H'
 'H' 'H' 'H' 'D' 'D' 'D' 'D' 'D' 'H' 'D' 'D' 'D' 'A' 'A' 'H' 'D' 'H' 'H'
 'H' 'H' 'A' 'D' 'H' 'H' 'H' 'D' 'H' 'A' 'D' 'H' 'D' 'D' 'H' 'D' 'D' 'H'
 'A' 'A' 'H' 'H' 'D' 'D' 'A' 'H' 'A' 'H' 'H' 'D' 'H' 'A' 'D' 'H' 'A' 'H'
 'D' 'H' 'D' 'A' 'D' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'H'
 'H' 'H' 'H' 'D' 'H' 'H' 'A' 'A' 'D' 'D' 'D' 'H' 'H' 'H' 'D' 'H' 'D' 'H'
 'H' 'A' 'D' 'H' 'A' 'H' 'H' 'D' 'H' 'D' 'A' 'H' 'H' 'A' 'H' 'H' 'D' 'H'
 'H' 'A' 'A' 'H' 'D' 'H' 'A' 'D' 'H' 'H' 'D' 'H' 'H' 'H' 'D' 'D' 'H' 'D'
 'D' 'A' 'A' 'H' 'H' 'A' 'H' 'A' 'H' 'H' 'H' 'A' 'A' 'H' 'A' 'H' 'H' 'A'
 'H' 'H' 'D' 'H' 'D' 'A' 'H' 'D' 'D' 'H' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H'
 'H' 'H' 'A' 'D' 'H' 'A' 'D' 'H' 'D' 'H' 'A' 'D' 'H' 'D' 'H' 'A' 'H' 'D'
 'H' 'D' 'H' 'H' 'A' 'H' 'D' 'D' 'D' 'A' 'H' 'H' 'H' 'D' 'H' 'A' 'D' 'H'
 'H' 'D' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'D' 'H' 'D' 'D' 'D' 'H' 'D' 'D'
 'H' 'H' 'D' 'D' 'D' 'H' 'H' 'D' 'H' 'H' 'H' 'A' 'D' 'H' 'H' 'A' 'H' 'H'
 'D' 'A' 'H' 'D' 'D' 'H' 'D' 'A' 'H' 'A' 'H' 'H' 'A' 'H' 'H' 'H' 'D' 'H'
 'H' 'H' 'A' 'H' 'A' 'D' 'A' 'D' 'D' 'H' 'H' 'H' 'H' 'A' 'D' 'A' 'H' 'D'
 'H' 'H' 'H' 'H' 'H' 'D' 'A' 'D' 'A' 'D' 'H' 'H' 'H' 'H' 'H' 'A' 'H' 'D'
 'H' 'A' 'A' 'A' 'A' 'D' 'D' 'D' 'H' 'H' 'H' 'D' 'A' 'H' 'A' 'H' 'H' 'A'
 'A' 'H' 'H' 'H' 'D' 'A' 'D' 'D' 'D' 'H' 'D' 'D' 'D' 'D' 'H' 'A' 'A' 'H'
 'D' 'A' 'H' 'D' 'H' 'D' 'H' 'H' 'D' 'H' 'H' 'H' 'D' 'D' 'H' 'A' 'H' 'D'
 'D' 'H' 'H' 'H' 'H' 'D' 'A' 'D' 'H' 'D' 'A' 'D' 'A' 'H' 'H' 'A' 'D' 'A'
 'D' 'H' 'D' 'H' 'D' 'D' 'D' 'D' 'D' 'A' 'H' 'D' 'D' 'H' 'D' 'H' 'H' 'D'
 'H' 'H' 'H' 'A' 'A' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'D' 'D' 'H' 'D' 'A'
 'A' 'A' 'H' 'H' 'H' 'H' 'D' 'D' 'H' 'H' 'A' 'H' 'D' 'D']

In [88]:
# We split the data even further 
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.3, random_state=42)

In [89]:
# Imports Classification Models
from sklearn.tree import DecisionTreeClassifier 
from sklearn.naive_bayes import GaussianNB 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.svm import SVC 
# Create an Empty List and append all models, Give the Models an alias Name 
# # i.e we called KNeighborsClassifier() alias KNC etc 
models = [] 
models.append(('D Trees', DecisionTreeClassifier())) 
models.append(('Gaussian', GaussianNB())) 
models.append(('KNC', KNeighborsClassifier())) 
models.append(('Random Forest', RandomForestClassifier())) 
models.append(('Gradient Boosting', GradientBoostingClassifier())) 
models.append(('Linear Disc', LinearDiscriminantAnalysis())) 
models.append(('Support Machines', SVC(gamma = 'auto'))) 
# Import Cross Validation and KFOLD 
from sklearn.model_selection import cross_val_score, KFold 
# Create a for loop so that each model is tested in turn 
for name, model in models: 
 # Here we do a 10 split K-FOLD - We split our data into 10 Folds 
 kfold = KFold(n_splits = 10, random_state=42, shuffle=True) 
 # We Train and Test the current model in the Loop 
 # Get the results for each Fold 
 cv_results = cross_val_score(model, X_train, Y_train, cv = kfold, scoring='accuracy') 
 # Get the average of all Folds For that specific model in the Loop
 print(name, ' Results:= ', cv_results.mean())

D Trees  Results:=  0.4342857142857143
Gaussian  Results:=  0.5142857142857142
KNC  Results:=  0.43142857142857133
Random Forest  Results:=  0.5428571428571429
Gradient Boosting  Results:=  0.5028571428571429
Linear Disc  Results:=  0.5857142857142856
Support Machines  Results:=  0.48

In [90]:
# import the model
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

model = LinearDiscriminantAnalysis()
model.fit(X_train, Y_train)

LinearDiscriminantAnalysis()

In [91]:
# Test model to see what it would predict
predictions = model.predict(X_test)
print("Model predictions: ", predictions)
print("values we expected: ", Y_test)

Model predictions:  ['H' 'H' 'A' 'H' 'H' 'H' 'D' 'A' 'D' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'A'
 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'D' 'H' 'D' 'D' 'H' 'H' 'D'
 'A' 'H' 'D' 'D' 'H' 'D' 'A' 'D' 'D' 'H' 'D' 'A' 'D' 'A' 'D' 'H' 'H' 'H'
 'D' 'D' 'H' 'D' 'H' 'H' 'A' 'A' 'H' 'H' 'H' 'A' 'H' 'H' 'D' 'H' 'H' 'H'
 'H' 'D' 'A' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'A' 'A' 'H' 'D' 'A' 'H' 'A'
 'A' 'D' 'H' 'D' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'H'
 'A' 'H' 'H' 'A' 'H' 'H' 'D' 'H' 'H' 'H' 'H' 'A' 'H' 'D' 'H' 'H' 'H' 'H'
 'D' 'D' 'D' 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'A' 'H' 'H' 'H' 'D' 'A' 'H'
 'D' 'H' 'D' 'D' 'H' 'H']
values we expected:  ['H' 'H' 'H' 'H' 'H' 'H' 'D' 'D' 'D' 'D' 'H' 'H' 'D' 'D' 'H' 'H' 'H' 'A'
 'H' 'D' 'H' 'H' 'H' 'D' 'H' 'D' 'H' 'H' 'D' 'H' 'D' 'A' 'H' 'H' 'H' 'A'
 'D' 'D' 'H' 'A' 'D' 'D' 'A' 'H' 'D' 'H' 'H ' 'A' 'A' 'A' 'D' 'D' 'D' 'H'
 'A' 'H' 'D' 'D' 'A' 'H' 'H' 'A' 'H' 'H' 'A' 'D' 'H' 'D' 'D' 'H' 'H' 'H'
 'D' 'D' 'A' 'D' 'H' 'D' 'D' 'H' 'H' 'H' 'H' 'D' 'A' 'H' 'H' 'D' 'H' 'D'
 'A' 'A' 'H' 'D' 'D' 'D' 'H' 'H' 'A' 'D' 'H' 'H' 'A' 'H' 'H' 'H' 'D' 'H'
 'A' 'A' 'D' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'A' 'A' 'H' 'D' 'H' 'H' 'H' 'A'
 'D' 'H' 'A' 'H' 'H' 'H' 'H' 'D' 'D' 'D' 'H' 'A' 'H' 'D' 'H' 'D' 'H' 'D'
 'H' 'H' 'A' 'H' 'H' 'D']

In [92]:
# Test the accuracy score of the model
from sklearn.metrics import accuracy_score
print("Accuracy: ", accuracy_score(Y_test, predictions))

Accuracy:  0.5866666666666667

In [93]:
# Predict using the correct variable name
suitability = [[42.4,33.2,0.79,0.98,20.6,15.3,89.2,87.8,1.26,1.07,0.15,0.33,0.52,3,4,1.25,1.11]]

outcome = model.predict(suitability)
print("The outcome will be: ", outcome)

The outcome will be:  ['H']